version: "3"
networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      my-network:
        ipv4_address: 172.23.0.2
    ports:
      - 1698:1698
      - 1699:1699
