# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.7.2-stretch

# Set and copy working directory
WORKDIR /app
ADD . /app

# Install pip requirements
ADD requirements.txt .
RUN pip install -r requirements.txt

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python", "server.py"]